core/urls.py
from django.urls import path
from .views import *
"""(
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView
)"""

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home/', HomeView.as_view(), name='overview'),
    path('home/search-result/', HomeViewSearchResult.as_view(), name='overview-search-result'),
    path('how-to/', display_how_to, name='how-to'),
    path('about-us/', display_about_us, name='about-us'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund')
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField


"""
Declare categories and filters by which the entities can be distinguished.
The main category is coat length, the additional categories are used as filters.
"""
CATEGORY_CHOICES = (
    ('SH', 'Short Hair'),
    ('MH', 'Medium Hair'),
    ('LH', 'Long Hair')
)

ENERGY_CHOICES = (
    ('LE', 'Low Energy'),
    ('ME', 'Medium Energy'),
    ('HE', 'High Energy')
)

SIZE_CHOICES = (
    ('S', 'Small Size'),
    ('M', 'Medium Size'),
    ('L', 'Large Size')
)

GENDER_CHOICES = (
    ('M', 'Boy'),
    ('F', 'Girl')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

# define global constants for min or max durations
MIN_RENTAL_HOURS = 5                # minimum rental duration in hours
MAX_RENTAL_DAYS = 7                 # maximum rental duration in days
MAX_PREORDER_DAYS = 14              # maximum days a cat can be ordered in advance (cat may not be available anymore!)
DEFAULT_RENTAL_DURATION = 1

# date format that is used in front-end
DATE_FORMAT = '%Y-%m-%dT%H:%M'

class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField(default = 4)
    #price = models.FloatField() TODO: could be used for different hourly rates ?
    #discount_price = models.FloatField(blank=True, null=True)
    available = models.BooleanField(default=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=ENERGY_CHOICES, max_length=2)
    size = models.CharField(choices=SIZE_CHOICES, max_length=1, default='NULL')
    gender = models.CharField(choices=GENDER_CHOICES, max_length=1, default='M')
    slug = models.SlugField()
    description = models.TextField()
    reviews = models.TextField(default="")
    image = models.ImageField()
    image2 = models.ImageField()
    image3 = models.ImageField()
    image4 = models.ImageField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

    def set_unavailable(self):
        self.available = False

    def set_available(self):
        self.available = True

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    
    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.item.price #self.quantity * self.item.price TODO: Clara - use rental duration and hourly rate?

    def get_duration(self):
        #if(hasattr(self, 'order')):
        if(True):
            return self.order_set.all()[0].get_rental_duration()
        else:
            return 1

    def get_total_discount_item_price(self):
        return 42 #self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return 42 #self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        """if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()"""
        #return 1
        return self.item.price * self.get_duration()

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    # start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    #from_date = models.DateTimeField(default=False)
    #to_date = models.DateTimeField(default=False)
    rental_duration = models.IntegerField(default=DEFAULT_RENTAL_DURATION)
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

    def get_rental_duration(self):
        return self.rental_duration


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)


post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <!-- Correct CSS references ?? -->
<!--
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="../static_in_env/css/bootstrap.css" rel="stylesheet">
  <link href="../static_in_env/css/mdb.css" rel="stylesheet">
  <link href="../static_in_env/css/style.css" rel="stylesheet">
-->
    {% comment %} datepickers {% endcomment %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.38.0/js/tempusdominus-bootstrap-4.min.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.38.0/css/tempusdominus-bootstrap-4.min.css" crossorigin="anonymous" />

  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 80vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>



</head>

{% include "navbar.html" %}

<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "footer.html" %}
    {% include "scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}

  <head>
      {% include "carousel.html" %}
  </head>

<script>
    function showCategory(category_string) {
        document.getElementById(category_string).style.display = 'block';
        document.getElementById('nav-item-' + category_string).classList.add("active");
    }
    function hideCategory(category_string) {
        document.getElementById(category_string).style.display = 'none';
        document.getElementById('nav-item-' + category_string).classList.remove("active");
    }
</script>

  <main>
    <div class="container">


      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand dark-grey-text">Coat Length: </span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <form class="collapse navbar-collapse" id="basicExampleNav" method="get">

          <!-- Categories -->
            <ul class="navbar-nav mr-auto">

                {% csrf_token %}
                <div class="btn-group mr-2" role="group">
                    {% for key, val in categories %}
                        <button type="submit" value="{{ key }}" name="category-filter" {% if choice == key %} class="btn btn-blue-grey active" {% else %} class="btn btn-outline-grey" {% endif %}>
                            {{ val }}
                        </button>
                    {% endfor %}
                </div>

                {% comment %} OLD FILTERS
                <li id="nav-item-ALL" class="nav-item active">
                  <a class="nav-link" href="#ALL" onclick="showCategory('ALL');hideCategory('SH');hideCategory('MH');hideCategory('LH')">All
                    <span class="sr-only">(current)</span>
                  </a>
                </li>
                <li id="nav-item-SH" class="nav-item">
                  <a class="nav-link" href="#SH" onclick="showCategory('SH');hideCategory('MH');hideCategory('LH');hideCategory('ALL')">Short Hair</a>
                </li>
                <li id="nav-item-MH" class="nav-item">
                  <a class="nav-link" href="#MH" onclick="showCategory('MH');hideCategory('SH');hideCategory('LH');hideCategory('ALL')">Medium Hair</a>
                </li>
                <li id="nav-item-LH" class="nav-item">
                  <a class="nav-link" href="#LH" onclick="showCategory('LH');hideCategory('SH');hideCategory('MH');hideCategory('ALL')">Long Hair</a>
                </li>
                {% endcomment %}

            </ul>

        </form>

          <!-- FILTERS -->
          <form method="get">
            {% csrf_token %}
            <select id="filter-size" class="form-control btn-outline-grey" name="size-filter" onchange="this.form.submit();">
                <option value="ALL" onclick='window.location.href="/home"'>Filter by size</option>
                {% for key, val in sizes %}
                    <option value="{{ key }}" {% if choice == key %} selected=selected {% endif %}>
                        {{ val }}
                    </option>
                {% endfor %}
            </select>
          </form>
      {% comment %} protected spacing {% endcomment %}
      &nbsp;&nbsp;
          <form method="get">
            {% csrf_token %}
            <select id="filter-attribute" class="form-control btn-outline-grey" name="attribute-filter" onchange="this.form.submit();">
                <option value="ALL"> Filter by energy</option>
                {% for key, val in energies %}
                    <option value="{{ key }}" {% if choice == key %} selected=selected {% endif %}>
                        {{ val }}
                    </option>
                {% endfor %}
            </select>
        </form>
        {% comment %}
          TODO: search function?
          <form class="form-inline">
            <form class="md-form my-0" method="POST" action="home/search-result/">
                {% csrf_token %}
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <input type="submit" value="Search">
            </form>
          </form>
        {% endcomment %}

      </nav>
      <!--/.Navbar-->

      <!--Section: Items -->
      <section id="ALL" class="text-center mb-4">

        <div class="row wow fadeIn">

          {% for item in object_list %}

              <div class="col-lg-3 col-md-6 mb-4">

                <div class="card">

                  <div class="view overlay">
                    <img src="{{ item.image.url }}" class="card-img-top">
                    <a href="{{ item.get_absolute_url }}">
                      <div class="mask rgba-white-slight"></div>
                    </a>
                  </div>

                  <div class="card-body text-center">
                    <a href="" class="dark-grey-text">
                      <h3>{{ item.title }}</h3>
                    </a>
                    <h5>
                      <strong>
                        <a href="{{ item.get_absolute_url }}" class="dark-grey-text">
                          <!-- <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span> -->
                          <span class="badge badge-pill purple">{{ item.get_category_display }}</span>
                          <span class="badge badge-pill primary-color">{{ item.get_size_display }}</span>
                          <span class="badge badge-pill secondary-color">{{ item.get_label_display }}</span>
                          <span class="badge badge-pill btn-dark">{{ item.get_gender_display }}</span>
                        </a>
                      </strong>
                    </h5>

                    {% if item.available %}
                    <h4 class="font-weight-bold green-text">
                        <strong>AVAILABLE</strong>
                    </h4>
                    {% else %}
                    <h4 class="font-weight-bold blue-grey-text">
                      <strong>TAKEN</strong>
                    </h4>
                    {% endif %}

                  </div>

                </div>

              </div>

          {% endfor %}
        </div>

      </section>
      <!--Section: Items -->

      <!--Pagination-->

      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}

          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      {% endif %}

    </div>
  </main>

{% endblock content %}

templates/navbar.html
{% load cart_template_tags %}

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="/">
        <strong class="blue-text">Rent A Cat</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li id="nav-item-Overview" {% if request.path == '/home/' %} class="nav-item active" {% else %} class="nav-item"  {% endif %}>
            <a class="nav-link waves-effect" href="/home">Overview
              <span class="sr-only">(current)</span>
            </a>
          <li id="nav-item-HowTo" {% if request.path == '/how-to/' %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
            <a class="nav-link waves-effect" href="/how-to">How To</a>
          </li>
          <li id="nav-item-About Us" {% if request.path == '/about-us/' %} class="nav-item active" {% else %} class="nav-item" {% endif %}>
            <a class="nav-link waves-effect" href="/about-us" onclick="setActive('AboutUs');setInactive('HowTo');setInactive('Overview')">About Us</a>
          </li>
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'core:order-summary' %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1"> {{ request.user|cart_item_count }} </span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_logout' %}">
              <span class="clearfix d-none d-sm-inline-block"> Logout </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_login' %}">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{% url 'account_signup' %}">
              <span class="clearfix d-none d-sm-inline-block"> Signup </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </div>

    </div>
  </nav>

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cats</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <div>
        <h6 class="my-0"> {{ order_item.item.title}}</h6>
        <small class="text-muted">{{ order_item.item.description}}</small>
        </div>
        <span class="text-muted">{{ order_item.get_final_price }} €</span>
    </li>
    {% endfor %}
    <!--{% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">{{ order.coupon.amount }}€</span>
    </li>
    {% endif %}-->
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (EUR)</span>
        <strong>{{ order.get_total }} €</strong>
    </li>
    </ul>
    <!--
    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}
    -->
</div>

templates/order_summary.html
{% extends "base.html" %}

{% block content %}
  <main>
    <div class="container">

    <div class="table-responsive text-nowrap">
    <h2>Order Summary</h2>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Item title</th>
            <!--<th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>-->
        </tr>
        </thead>
        <tbody>
        {% for order_item in object.items.all %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.item.title }}</td>

            <!-- <td>{{ order_item.item.price }}</td> 
            <td>
                <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fas fa-minus mr-2"></i></a>
                {{ order_item.quantity }}
                <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>-->
            
            <td>
            <!--
            {% if order_item.item.discount_price %}
                ${{ order_item.get_total_discount_item_price }}
                <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
            {% else %}
                ${{ order_item.get_total_item_price }}
            {% endif %}
            -->
            <a style='color: red;' href="{% url 'core:remove-from-cart' order_item.item.slug %}">
                <i class="fas fa-trash float-right"></i>
            </a>
            </td>
        </tr>
        {% empty %}
        <tr>
            <td colspan='5'>Your cart is empty</td>
        </tr>
        {% endfor %}
        <!--{% if object.coupon %}
        <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
        </tr>
        {% endif %}-->
        <tr>
            <td colspan="5">
            <a class='btn btn-warning float-right ml-2' href='/checkout/'>Proceed to checkout</a>
            <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
        </tr>
        
        </tbody>
    </table>

    </div>

    </div>
  </main>

{% endblock content %}

templates/product.html
{% extends "base.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column with primary cat image-->
        <div class="col-md-6 mb-4">
            <img src="{{ item.image.url }}" class="card-img-top">
        </div>

        <!--Grid column with badges, price and texts-->
        <div class="col-md-6 mb-4">

          <div class="p-4">
            <p class="my-1 h1">{{ object.title }}</p>
            <div class="mb-3">
              <a href="">
                <span class="badge badge-pill purple">{{ object.get_category_display }}</span>
                <span class="badge badge-pill primary-color">{{ item.get_size_display }}</span>
                <span class="badge badge-pill secondary-color">{{ item.get_label_display }}</span>
                <span class="badge badge-pill btn-dark">{{ item.get_gender_display }}</span>
              </a>
            </div>

            <p class="lead">
              <span class="mr-1">Rental fee: {{ object.price }} €/h</span>
            </p>

            <br></br>

            <p class="lead font-weight-bold">Description</p>

            <p class="lead">{{ object.description }}</p>
            
            <p class="lead font-weight-bold">Reviews</p>

            <p class="lead">{{ object.reviews|linebreaks }}</p>
            
            {% comment %} <form class="d-flex justify-content-left">
              <!-- Add to cart and remove from cart buttons -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Like me?</h4>

          <p></p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row with additional cat photos-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">
          <img src="{{ item.image2.url }}" class="img-fluid" alt="">
        </div>
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <img src="{{ item.image3.url }}" class="img-fluid" alt="">
        </div>
        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">
          <img src="{{ item.image4.url }}" class="img-fluid" alt="">
        </div>

      <!--Grid row-->

    </div>
  </main>

{% endblock content %}

templates/request_refund.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}